dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh | bash
notifications:
  slack:
    rooms:
      - secure: "bEuNkvjYIb5SoEnV4IWse39bKb8VhEk/O0ZWoioTrnVWJhaH1h2YiojqiVmjoXqSYDJYDMyGgVR4Gl9+AcfbwAIvHrXgfc+asjIuIAJb1Yf/YiHK7dwYIJUGycgWFSWjTMjO+5PmKaKHX0ePzRSvgwXdv7MkgB7wXBTNLg3myjHjRNgUyAoXZhZNa3pf5QxZxrd1mAo1eW9swzqPGDMCJqnGiBaw+n9hmyBCkecQWxQPTh1rJkF7JMj3/tbuzMCOCFB3P72mBloHQJ8Jq87WNyhzhoC7NuG4uo0YYNhAEYk4J+lSOLFt8TNmuJGGLaUOY+alWaAe15bCjsCdGpPSEPGRJmRB3Zq+i17suLthT+GpPPTq7mA3PmmWYZXtsPHuJDS4kAuLmmOmqb/h+BxXpkl2uDOQaT8LVckFxOnwlapEp9ifhkbNQ5q2TaDYNPtPo24PScpjLBuSRB1IEtdZF82udS13ASA5SLyxTO8SkE5QHotEXrswXCi0WlIBiGJRA42/6Nd8m5m2r1bUAX5asevq+2U7A0EeP5nAu2l8ZEOirAdH3H4Hf+/7rqVsgSUNCKK/yJebXKIgIWxlpCGhqEW29JTbn/5Q3CW6lDq7qdG4QL78FizA3+AZjbMDAfgbG7gS4hQMyvQeBhMXQX8+cUcVZV1tjbEirvUI2WYkrPg="
