dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh | bash
notifications:
  slack:
    rooms:
secure: ilsC/cq2U/mZNPhird38J4A7tXtGBzGw2yokNYjJsxzNbQz38+lVqmlYPqgsLbFHWW1Y7d603hoLgBS5ai6qlODJ6gFLPrlAHtnP7fzJfv8C9MyIjoh+rkrOiFJRt1ZfYbIBgv/C4ygVI/7kfJG+Nppf0MC66sgddppef0mpoLjNtlsCH82xTXiF7ywa+3XIlBzAvg562hlELsZ4a5yWrHTJAUcfebxZLYajJz1UI6czqKBwVUhfB7lW5QGij6rITgP6FKK30u8Dr3MRX7opVAkFZ9bJTT+CEwmQTS2pZvF8Hzp8ASmK0Kbg7g0YPw9n38J3CWP1CdpRxnrA6K9J74WLAHGq+x3JXelVLferuPU8dUkJ7V6DPejh6ZpOfKecC14futhfabwcX+kEPt+BKhLBt1klmf3m/EVl1137SFD6HzgSzllwM7HEFKeLYQIE/rcu1WkwGtXcdqQiTE8QxAaMgc13DE5M2fofSuPsL0COEA7yIGMyV383EX57atWgUAvz5K3hd7v2aqjOi8+F8JKKRFjtsJ3/402H6q/U/+lwfvYLfuCIsCbjQKwfA0Z529j8xWLAGpk+G/3tVF4PTCT5utWCuHG/U5h1jhi1TLbAJQAyuaFzGqLCiZisKAYtKdjItQUx1A1QzAYTLnv7IfYNzHrKLaJ72PZhv25n2CQ=
