dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh | bash
notifications:
  slack:
    rooms:
      secure: "Sc+XdoPoS2enJeYCpnFYKBtYsZLDSbJVleXUl+zGzmlU7W5Yo7KZqtI9QHQH/KfJ8vdRhQ5SigpxkjKi+FsM8VheQ6oJjZrxds63F0jrRFx/D+tgD1KLNM6dV0C6uYnmJK6t5mQSxbkAEfAggNPwUQPBI5t1ls7Xe62DBafKOjcxxzblbECr/bBMIgW04zpuF2kCv0ij8iDu0o3yRWdpZ7qOOES+LA3MfoO3DzAHrJgN0kBOrylEKX5p2SkVrCXaudP67ZtAJpo7QQWpQM2GUszHpw3FkgZtaPcv/cQKAHPTK7qCRCShnrLlyYSILSlwaM7qBTiEviSjGOy8yA2wmLCyQxmT+BG/GMZc9PMMQ5nNr9M9mtDN01qM+CI5M9u+OHyFDKzUGjv9DTc7nSbUHqn9IdRcuWw/AUKel8Maulz1q4Qisg6zHarCDO2W+WxL3AvJH7EmG3R1SuXRQAl1r4aSzJtCPhXyNrgcSOcwZxYN0Byhvhx4P7zsbCcm7cS1JRL80hYEockY1TWbdcN2f3cvIInypTinIq82N8j+t4oVf7nlCDNnUbX6Gsr1puJ/p+UnvMRJvfqbEqg0Bz5wYIqlBLnOu9sA8akz3pdrAyxqflDR1QsVkPCbdH8TcqxhMcAMC3bSWuj9nlzYUwrHM5clx3Hw4szTWrugyptqGNw="
